name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - uses: actions/checkout@v3
    
    - name: dependencies
      run: |
        dkp-pacman -S libcurl
        git clone --recursive https://github.com/dimok789/libiosuhax.git
        cd libiosuhax
        make
        make install
        cd ..
        git clone --recursive https://github.com/wtfloltk/libfat.git libfat2
        cd libfat2
        ls include
        cd wiiu
        make
        make install
        cd ..
        cd ..
        git clone --recursive https://github.com/Maschell/dynamic_libs.git
        cd dynamic_libs
        git clone --recursive https://github.com/curl/curl.git include/curl
        make
        make install
        cd ..
        git clone --recursive https://github.com/Maschell/libutils.git
        cd libutils
        make
        make install
        cd ..
        git clone --recursive https://github.com/Maschell/libgui.git
        cd libgui
        make
        make install
        cd ..
        
    - name: make
      run: make

    - uses: actions/upload-artifact@master
      with:
        name: wupl
        path: build
      
